---
title: "Data products"
author: "Ansh Tiwari"
date: "10/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# October 23, 2020

```{r chunk 1}
place <- c("16 Buckkingham Drivee", "Eastamppton Commmunity Scchool", "Rrancocas Vaalley Rregional Hiigh Schoool", "Buttoonwood Paark", "Ruutgers Uuniversity", "Uuniversity oof California, Los Anglees", "10941 Strathmore Drive", "Aurora", "Coffee Bean", "many dollars speent, maany boooks uunread, muuch muusic heeard", "St.. Aggnes Hoospital", "Taalvandi Araain", "Siialkot, Puunjab", "Dhaaramsala, Himaachal Praadesh", "Maagnolia Hootel", "Wuu Tangg Klaang", "Shriine oif Bulllhe Shaah", "Stt. Joseeph Hoospital", "Laahore, Puunjab", "Raatajoa (Poool oof Bloood)" )
place_links <- c("<a href='https://www.gps-coordinates.net/street-view/@39.992445,-74.765458,h182,p5,z1'>Home</a>", "<a href='http://www.eastampton.k12.nj.us/'>Primary</a>", "<a href='http://rvrhs.com/'>High School</a>", "<a href='https://www.youtube.com/watch?v=WH_PC4UOoY4'>Tennis</a>", "<a href='http://newbrunswick.rutgers.edu/?utm_source=rutgers.edu&utm_medium=web&utm_campaign=uwide_sliver'>College</a>", "<a href='http://socialsciences.ucla.edu/departments/'>UCLA</a>", "<a href='https://en.wikipedia.org/wiki/Bhavacakra'>Westwood</a>", "<a href='http://cherrycreekschools.org/Pages/default.aspx'>Centennial</a>", "<a href='https://psychcentral.com/blog/archives/2012/04/15/caffeines-effects-on-your-thinking/'>many cups of joe</a>", "<a href='https://shop.uclastore.com/c-318-bookzone.aspx'>many dollars spent, many books unread</a>", "<a href='http://www.stagnes.org/150/'>where it all began</a>", "<a href='https://en.wikipedia.org/wiki/Partition_of_India'>daadkay dee praanee pind</a>", "<a href='https://en.wikipedia.org/wiki/Sialkot'>Ami day naandkay</a>", "<a href='https://www.youtube.com/watch?v=nWY0Tyhu9MM'>Madhyamaka</a>", "<a href='http://www.starwoodhotels.com/gx/property/overview/index.html?propertyID=4703&SWAQ=958P'>The Special Day</a>", "<a href='https://en.wikipedia.org/wiki/Klang_(city)'>Klang</a>", "<a href='https://www.youtube.com/watch?v=B-pTz8ZM0nw'>Bullhe Shah</a>", "<a href='https://www.sclhealth.org/locations/saint-joseph-hospital/'>My Seeds</a>", "<a href='https://en.wikipedia.org/wiki/Lahore'>Lahore</a>", "<a href='http://press.princeton.edu/titles/4250.html'>Pind</a>")
lat <- c(39.9921999, 39.99891909999999, 40.0024695, 39.99760750000001, 40.5203204, 34.068921,
         34.0672062, 39.615245, 39.615245, 34.0627396, 39.9260163, 31.5188331, 31.5188331, 
         32.5179603, 32.21904200000001, 3.044917, 31.12107223150165, 39.7464498, 31.4054167, 31.1914511)
lng <- c(-74.7654999999999, -74.7545756000000, -74.782902, -74.763331, -74.4359104999999,
         -118.4451811000000, -118.4500780000000, -104.7955359999999, -118.4450413999999, -118.4445650000000, 
         -75.169796, 75.7465975000000, 74.5009168000000, 76.3234036999999, -104.9923514000000,
         101.4455620999999, 74.4476938247680, -104.971597, 74.1636313000000, 74.0579185000000)
df <- data.frame(place, place_links, lat, lng)
library(leaflet)
df %>%
  leaflet() %>%
  addTiles() %>%
  addMarkers(lat=lat, lng=lng, popup=place_links, clusterOptions=markerClusterOptions)
```